################################################################################
#   SECTION: Capabilities
################################################################################
Capabilities:
    Channel: &ChannelCapabilities
        V2_0: true
    Orderer: &OrdererCapabilities
        V2_0: true
    Application: &ApplicationCapabilities
        V2_0: true

################################################################################
#   CHANNEL Defaults
################################################################################
Channel: &ChannelDefaults
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
    Capabilities:
        <<: *ChannelCapabilities

################################################################################
#   Section: Organizations
################################################################################
Organizations:
    - &detran
      Name: detranMSP
      ID: detranMSP
      MSPDir: crypto-config/peerOrganizations/detran.car-lifes-cycle.com/msp

      Policies:
          Readers:
              Type: Signature
              Rule: "OR('detranMSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('detranMSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('detranMSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('detranMSP.member')"

      AnchorPeers:
          - Host: peer0.detran.car-lifes-cycle.com
            Port: 7021

    - &gov
      Name: govMSP
      ID: govMSP
      MSPDir: crypto-config/peerOrganizations/gov.car-lifes-cicle.com/msp

      Policies:
          Readers:
              Type: Signature
              Rule: "OR('govMSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('govMSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('govMSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('govMSP.member')"

      AnchorPeers:
          - Host: peer0.gov.car-lifes-cicle.com
            Port: 7041

    - &montadoraC
      Name: montadoraCMSP
      ID: montadoraCMSP
      MSPDir: crypto-config/peerOrganizations/montadora-c.car-lifes-cicle.com/msp

      Policies:
          Readers:
              Type: Signature
              Rule: "OR('montadoraCMSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('montadoraCMSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('montadoraCMSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('montadoraCMSP.member')"

      AnchorPeers:
          - Host: peer0.montadora-c.car-lifes-cicle.com
            Port: 7061

    - &montadoraD
      Name: montadoraDMSP
      ID: montadoraDMSP
      MSPDir: crypto-config/peerOrganizations/montadora-d.car-lifes-cicle.com/msp

      Policies:
          Readers:
              Type: Signature
              Rule: "OR('montadoraDMSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('montadoraDMSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('montadoraDMSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('montadoraDMSP.member')"

      AnchorPeers:
          - Host: peer0.montadora-d.car-lifes-cicle.com
            Port: 7081

    - &concessionariaF
      Name: concessionariaFMSP
      ID: concessionariaFMSP
      MSPDir: crypto-config/peerOrganizations/concessionaria-f.car-lifes-cicle.com/msp

      Policies:
          Readers:
              Type: Signature
              Rule: "OR('concessionariaFMSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('concessionariaFMSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('concessionariaFMSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('concessionariaFMSP.member')"

      AnchorPeers:
          - Host: peer0.concessionaria-f.car-lifes-cicle.com
            Port: 7101

    - &concessionariaG
      Name: concessionariaGMSP
      ID: concessionariaGMSP
      MSPDir: crypto-config/peerOrganizations/concessionaria-g.car-lifes-cicle.com/msp

      Policies:
          Readers:
              Type: Signature
              Rule: "OR('concessionariaGMSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('concessionariaGMSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('concessionariaGMSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('concessionariaGMSP.member')"

      AnchorPeers:
          - Host: peer0.concessionaria-g.car-lifes-cicle.com
            Port: 7121

    - &mecanicaK
      Name: mecanicaKMSP
      ID: mecanicaKMSP
      MSPDir: crypto-config/peerOrganizations/mecanica-k.car-lifes-cicle.com/msp

      Policies:
          Readers:
              Type: Signature
              Rule: "OR('mecanicaKMSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('mecanicaKMSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('mecanicaKMSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('mecanicaKMSP.member')"

      AnchorPeers:
          - Host: peer0.mecanica-k.car-lifes-cicle.com
            Port: 7141

    - &mecanicaL
      Name: mecanicaLMSP
      ID: mecanicaLMSP
      MSPDir: crypto-config/peerOrganizations/mecanica-l.car-lifes-cicle.com/msp

      Policies:
          Readers:
              Type: Signature
              Rule: "OR('mecanicaLMSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('mecanicaLMSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('mecanicaLMSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('mecanicaLMSP.member')"

      AnchorPeers:
          - Host: peer0.mecanica-l.car-lifes-cicle.com
            Port: 7161

    - &financiadoraR
      Name: financiadoraRMSP
      ID: financiadoraRMSP
      MSPDir: crypto-config/peerOrganizations/financiadora-r.car-lifes-cicle.com/msp

      Policies:
          Readers:
              Type: Signature
              Rule: "OR('financiadoraRMSP.member')"
          Writers:
              Type: Signature
              Rule: "OR('financiadoraRMSP.member')"
          Admins:
              Type: Signature
              Rule: "OR('financiadoraRMSP.admin')"
          Endorsement:
              Type: Signature
              Rule: "OR('financiadoraRMSP.member')"

      AnchorPeers:
          - Host: peer0.financiadora-r.car-lifes-cicle.com
            Port: 7181

################################################################################
#   SECTION: Application
################################################################################
Application: &ApplicationDefaults
    Organizations:
    # Policies defines the set of policies at this level of the config tree
    # For Application policies, their canonical path is
    #   /Channel/Application/<PolicyName>
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        Endorsement:
            Type: ImplicitMeta
            Rule: "ANY Writers"
    Capabilities:
        <<: *ApplicationCapabilities

################################################################################
#   SECTION: Orderer
################################################################################
Orderer: &Orderers-groupDefaults
    OrdererType: solo
    Addresses:
        - orderer0.orderers-group.detran.car-lifes-cycle.com:7030
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Organizations:
    # Policies defines the set of policies at this level of the config tree
    # For Orderer policies, their canonical path is
    #   /Channel/Orderer/<PolicyName>
    Policies:
        Readers:
            Type: ImplicitMeta
            Rule: "ANY Readers"
        Writers:
            Type: ImplicitMeta
            Rule: "ANY Writers"
        Admins:
            Type: ImplicitMeta
            Rule: "MAJORITY Admins"
        # BlockValidation specifies what signatures must be included in the block
        # from the orderer for the peer to validate it.
        BlockValidation:
            Type: ImplicitMeta
            Rule: "ANY Writers"
    Capabilities:
        <<: *OrdererCapabilities

################################################################################
#   Profile
################################################################################
# https://github:com/hyperledger/fabric/blob/master/sampleconfig/configtx.yaml

Profiles:
    # Profile used to create Genesis block for group orderers-group #
    Orderers-groupGenesis:
        <<: *ChannelDefaults
        Orderer:
            <<: *Orderers-groupDefaults
            Organizations:
                - *detran
            Capabilities:
                <<: *OrdererCapabilities
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *detran
                    - *gov
                    - *montadoraC
                    - *montadoraD
                    - *concessionariaF
                    - *concessionariaG
                    - *mecanicaK
                    - *mecanicaL
                    - *financiadoraR

    # Profile used to create channeltx for car-channel #
    CarChannel:
        <<: *ChannelDefaults
        Orderer:
            <<: *Orderers-groupDefaults
            Organizations:
                - *detran
            Capabilities:
                <<: *ApplicationCapabilities
        Consortium: SampleConsortium
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *detran
                    - *gov
                    - *montadoraC
                    - *montadoraD
                    - *concessionariaF
                    - *concessionariaG
                    - *mecanicaK
                    - *mecanicaL
                    - *financiadoraR
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *detran
                - *gov
                - *montadoraC
                - *montadoraD
                - *concessionariaF
                - *concessionariaG
                - *mecanicaK
                - *mecanicaL
                - *financiadoraR

    # Profile used to create channeltx for person-channel #
    PersonChannel:
        <<: *ChannelDefaults
        Orderer:
            <<: *Orderers-groupDefaults
            Organizations:
                - *detran
            Capabilities:
                <<: *ApplicationCapabilities
        Consortium: SampleConsortium
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *detran
                    - *gov
                    - *montadoraC
                    - *montadoraD
                    - *concessionariaF
                    - *concessionariaG
                    - *mecanicaK
                    - *mecanicaL
                    - *financiadoraR
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *detran
                - *gov
                - *montadoraC
                - *montadoraD
                - *concessionariaF
                - *concessionariaG
                - *mecanicaK
                - *mecanicaL
                - *financiadoraR
